name: running test,build image, push registry, deploy
on:
  push:
    branches: [main]

jobs:
  runningtest:
    name: running test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.2'
      - name: run test
        run: go test -v ./... -cover

  buildimage:
    name: build image
    runs-on: ubuntu-latest
    needs: runningtest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create env
        run: |
          echo " ${{ secrets.ENV_PROJECT }} " > .env
      - name: build image
        run: docker build -t chandrawr/mini_project:latest .
      - name: login registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push chandrawr/mini_project:latest

  deployec2:
    name: deploy ec2
    runs-on: ubuntu-latest
    needs: buildimage
    steps:
      - uses: actions/checkout@v2
      - name: deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/mini-project
            docker pull chandrawr/mini_project:latest
            docker run -d -p 8080:8080 chandrawr/mini_project:latest